#!/usr/bin/env node
/**
 * github-push.js — Create a GitHub repo and push all files from a dist directory.
 * Uses the Git Data API (no local git required).
 *
 * Usage: node github-push.js <repo-name> <dist-dir> [description]
 */

import https from 'https';
import fs from 'fs';
import path from 'path';
import { readFileSync } from 'fs';

// Load .env
const envPath = new URL('.env', import.meta.url).pathname;
const envVars = {};
if (fs.existsSync(envPath)) {
  readFileSync(envPath, 'utf8').split('\n').forEach(line => {
    const eqIdx = line.indexOf('=');
    if (eqIdx > 0) envVars[line.slice(0, eqIdx).trim()] = line.slice(eqIdx + 1).trim();
  });
}

const GH_TOKEN = process.env.GITHUB_TOKEN || envVars.GITHUB_TOKEN;
const repoName = process.argv[2];
const distDir  = path.resolve(process.argv[3] || 'dist');
const desc     = process.argv[4] || 'Generated by PersonArchive';

function ghReq(method, urlPath, body) {
  return new Promise((resolve, reject) => {
    const data = body ? JSON.stringify(body) : null;
    const opts = {
      hostname: 'api.github.com',
      path: urlPath,
      method,
      headers: {
        'Authorization': `token ${GH_TOKEN}`,
        'User-Agent': 'PersonArchive/0.1',
        'Accept': 'application/vnd.github+json',
        ...(data && { 'Content-Type': 'application/json', 'Content-Length': Buffer.byteLength(data) })
      }
    };
    const req = https.request(opts, res => {
      const chunks = [];
      res.on('data', c => chunks.push(c));
      res.on('end', () => {
        let parsed;
        try { parsed = JSON.parse(Buffer.concat(chunks).toString()); } catch { parsed = {}; }
        resolve({ status: res.statusCode, body: parsed });
      });
    });
    req.on('error', reject);
    if (data) req.write(data);
    req.end();
  });
}

function collectFiles(dir, base = dir) {
  const files = [];
  const SKIP = new Set(['.git', 'node_modules', '.DS_Store', '.env']);
  for (const entry of fs.readdirSync(dir)) {
    if (SKIP.has(entry)) continue;
    const abs = path.join(dir, entry);
    if (fs.statSync(abs).isDirectory()) {
      files.push(...collectFiles(abs, base));
    } else {
      files.push({ rel: path.relative(base, abs), abs });
    }
  }
  return files;
}

async function main() {
  console.log(`\n🐙 GitHub Push: ${repoName}`);

  // 1. Get current user
  const userRes = await ghReq('GET', '/user');
  const username = userRes.body.login;
  console.log(`   User: @${username}`);

  // 2. Create repo (or verify it exists)
  console.log(`\n1️⃣  Creating repo "${repoName}"...`);
  const createRes = await ghReq('POST', '/user/repos', {
    name: repoName,
    description: desc,
    private: false,
    auto_init: false
  });

  let repoUrl;
  if (createRes.status === 201) {
    repoUrl = createRes.body.html_url;
    console.log(`   ✅ Created: ${repoUrl}`);
  } else if (createRes.status === 422 && createRes.body.errors?.some(e => e.message?.includes('already exists'))) {
    repoUrl = `https://github.com/${username}/${repoName}`;
    console.log(`   ℹ️  Repo already exists: ${repoUrl}`);
  } else {
    throw new Error(`Failed to create repo: ${JSON.stringify(createRes.body).substring(0, 300)}`);
  }

  // 3. Collect all files
  console.log(`\n2️⃣  Collecting files from ${distDir}...`);
  const files = collectFiles(distDir);
  console.log(`   Found ${files.length} file(s)`);

  // 4. Create blobs for each file
  console.log(`\n3️⃣  Uploading file blobs...`);
  const blobs = [];
  for (const { rel, abs } of files) {
    const content = fs.readFileSync(abs);
    const encoding = /\.(png|jpg|ico|woff2|woff|ttf)$/.test(abs) ? 'base64' : 'utf-8';
    const blobRes = await ghReq('POST', `/repos/${username}/${repoName}/git/blobs`, {
      content: encoding === 'base64' ? content.toString('base64') : content.toString('utf8'),
      encoding
    });
    if (blobRes.status !== 201) throw new Error(`Blob failed for ${rel}: ${JSON.stringify(blobRes.body)}`);
    blobs.push({ path: rel, mode: '100644', type: 'blob', sha: blobRes.body.sha });
    console.log(`   ✅ ${rel}`);
  }

  // 5. Create a tree
  console.log(`\n4️⃣  Creating git tree...`);
  const treeRes = await ghReq('POST', `/repos/${username}/${repoName}/git/trees`, { tree: blobs });
  if (treeRes.status !== 201) throw new Error(`Tree creation failed: ${JSON.stringify(treeRes.body)}`);
  const treeSha = treeRes.body.sha;
  console.log(`   ✅ Tree: ${treeSha.slice(0, 8)}…`);

  // 6. Create a commit
  console.log(`\n5️⃣  Creating commit...`);
  const commitRes = await ghReq('POST', `/repos/${username}/${repoName}/git/commits`, {
    message: 'Initial archive deploy via PersonArchive',
    tree: treeSha,
    parents: []
  });
  if (commitRes.status !== 201) throw new Error(`Commit failed: ${JSON.stringify(commitRes.body)}`);
  const commitSha = commitRes.body.sha;
  console.log(`   ✅ Commit: ${commitSha.slice(0, 8)}…`);

  // 7. Create/update main branch ref
  console.log(`\n6️⃣  Pushing to main branch...`);
  const refCreateRes = await ghReq('POST', `/repos/${username}/${repoName}/git/refs`, {
    ref: 'refs/heads/main',
    sha: commitSha
  });

  if (refCreateRes.status === 201) {
    console.log(`   ✅ Branch main created`);
  } else if (refCreateRes.status === 422) {
    // Ref exists — force update
    const refUpdateRes = await ghReq('PATCH', `/repos/${username}/${repoName}/git/refs/heads/main`, {
      sha: commitSha, force: true
    });
    if (refUpdateRes.status !== 200) throw new Error(`Ref update failed: ${JSON.stringify(refUpdateRes.body)}`);
    console.log(`   ✅ Branch main updated`);
  } else {
    throw new Error(`Ref creation failed: ${JSON.stringify(refCreateRes.body)}`);
  }

  console.log(`\n✅ Pushed to GitHub: ${repoUrl}\n`);
  return repoUrl;
}

main().catch(err => { console.error('Fatal:', err.message); process.exit(1); });
